Introduction to pandas: Series, DataFrame, data manipulation

Pandas Overview

Pandas is a powerful Python library for data manipulation and analysis. It provides two primary data structures: Series and DataFrame.

Installation: You can install Pandas using pip:
    pip install pandas

    Series

    Series is a one-dimensional labeled array capable of holding any data type. It is similar to a one-dimensional NumPy array but with additional functionality and a labeled index.

In [1]:
#Code Example:
import pandas as pd

s = [1,2,3,"Angel",4,5]
# Creating a Series from a Python list
S = pd.Series(s)
print(S)

0        1
1        2
2        3
3    Angel
4        4
5        5
dtype: object

DataFrame
DataFrame is a two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table.

In [ ]:
df = {'name':["Harriet", "Rashid", "Olalode"],
 'age':[59,45,34],
 'Location':["Boston", "Saskastchwan", "Colombus"]
 }

data = pd.DataFrame(df)
print(data)

      name  age      Location
0  Harriet   59        Boston
1   Rashid   45  Saskastchwan
2  Olalode   34      Colombus

In [3]:
#Code Example:
# Creating a DataFrame from a dictionary
data = {'Name': ['John', 'Alice', 'Bob'],
        'Age': [30, 25, 35],
        'City': ['New York', 'Paris', 'London']}
df = pd.DataFrame(data)
print(df)

    Name  Age      City
0   John   30  New York
1  Alice   25     Paris
2    Bob   35    London

Data Manipulation
Indexing and Slicing: You can access and manipulate data in Series and DataFrame using indexing and slicing.
Indexing: access one item
Slicing: access a range of items

In [4]:
s = pd.Series([1, 2, 3, 4, 5])
# Accessing elements in a Series
print(s[3]) # Accessing the first element

4

In [5]:
x = {'Name':["Harriet", "Rashid", "Olalode"],
     'Age': [30, 25, 35],
     'City': ['New York', 'Paris', 'London']}

df = pd.DataFrame(x)
print(df)

# Slicing a DataFrame
df[['Name']]  # Accessing a column

df[['Age']]

      Name  Age      City
0  Harriet   30  New York
1   Rashid   25     Paris
2  Olalode   35    London

   Age
0   30
1   25
2   35

In [6]:
type(df['Age'])

pandas.Series

In [7]:
type(df[['Age']])

pandas.DataFrame

Data Combination: is the process of joining, merging or concatenating multiple pandas data structure into a single data structure.
The most common ways of combine dataframes are concatenation, joining and merge

Concatenation
Using the `concat` function to combine two or more dataframes with the same columns either vertically or horizontally.

In [30]:
df_1 = pd.DataFrame({'A': [4, 2, 6,], 'B': ['m', 'n', 'o']})
df_2 = pd.DataFrame({'A': [45, 8, 9], 'B': ['x', 'y', 'z']})

df_1

   A  B
0  4  m
1  2  n
2  6  o

In [10]:
df_2

    A  B
0  45  x
1   8  y
2   9  z

In [31]:
# Vertical concatenation (row-wise)
vertical_com = pd.concat([df_1, df_2], axis=0, keys=["df_1", "df_2"])
vertical_com

         A  B
df_1 0   4  m
     1   2  n
     2   6  o
df_2 0  45  x
     1   8  y
     2   9  z

In [12]:
# Horizontal concatenation (column-wise)
horizontal_com = pd.concat([df_1, df_2], axis=1, keys=["df_1","df_2"])
horizontal_com

  df_1    df_2
     A  B    A  B
0    4  m   45  x
1    2  n    8  y
2    6  o    9  z

In [13]:
vertical_com.loc["df_1"]

   A  B
0  4  m
1  2  n
2  6  o

In [16]:
vertical_com.loc["df_1",0]

A    4
B    m
Name: (df_1, 0), dtype: object

In [18]:
vertical_com.loc["df_1",0]["A":"B"]

A    4
B    m
Name: (df_1, 0), dtype: object

In [19]:
# Vertical concatenation (row-wise)
vertical_com = pd.concat([df_1, df_2], axis=0, ignore_index=True)
vertical_com

    A  B
0   4  m
1   2  n
2   6  o
3  45  x
4   8  y
5   9  z

In [20]:
# Horizontal concatenation (column-wise)
horizontal_com = pd.concat([df_1, df_2], axis=1, keys=["df_1","df_2"])
horizontal_com

  df_1    df_2
     A  B    A  B
0    4  m   45  x
1    2  n    8  y
2    6  o    9  z

In [21]:
horizontal_com["df_1"]

   A  B
0  4  m
1  2  n
2  6  o

In [22]:
horizontal_com["df_2"]

    A  B
0  45  x
1   8  y
2   9  z

In [23]:
horizontal_com["df_1"][["A","B"]]

   A  B
0  4  m
1  2  n
2  6  o

In [24]:
accra =pd.DataFrame({'Town':['Circle','Madina','East Legon'],
                    'Humidity':[32,29,34],
                    'Temperature':[28,30,25]})
kumasi =pd.DataFrame({'Town':['Kejetia','Amakom','Mantia'],
                    'Humidity':[27,39,36],
                    'Temperature':[30,26,24]})

In [25]:
df_3 = pd.concat([accra,kumasi], ignore_index=True)
df_3

         Town  Humidity  Temperature
0      Circle        32           28
1      Madina        29           30
2  East Legon        34           25
3     Kejetia        27           30
4      Amakom        39           26
5      Mantia        36           24

In [26]:
df_4 = pd.DataFrame({'Windspeed':[8,5,7,8,6,4,9,10,5]})
df_4

   Windspeed
0          8
1          5
2          7
3          8
4          6
5          4
6          9
7         10
8          5

In [27]:
pd.concat([df_3,df_4], ignore_index=True, axis=0)

          Town  Humidity  Temperature  Windspeed
0       Circle      32.0         28.0        NaN
1       Madina      29.0         30.0        NaN
2   East Legon      34.0         25.0        NaN
3      Kejetia      27.0         30.0        NaN
4       Amakom      39.0         26.0        NaN
5       Mantia      36.0         24.0        NaN
6          NaN       NaN          NaN        8.0
7          NaN       NaN          NaN        5.0
8          NaN       NaN          NaN        7.0
9          NaN       NaN          NaN        8.0
10         NaN       NaN          NaN        6.0
11         NaN       NaN          NaN        4.0
12         NaN       NaN          NaN        9.0
13         NaN       NaN          NaN       10.0
14         NaN       NaN          NaN        5.0

In [28]:
pd.concat([df_3,df_4], ignore_index=True, axis=1)

            0     1     2   3
0      Circle  32.0  28.0   8
1      Madina  29.0  30.0   5
2  East Legon  34.0  25.0   7
3     Kejetia  27.0  30.0   8
4      Amakom  39.0  26.0   6
5      Mantia  36.0  24.0   4
6         NaN   NaN   NaN   9
7         NaN   NaN   NaN  10
8         NaN   NaN   NaN   5